dbp_relay_mono_connector_payone_bundle:
  path: /mono-connector-payone/widget
  methods: ['GET']
  defaults:
    _controller: Dbp\Relay\MonoConnectorPayoneBundle\Controller\Widget::index

dbp_relay_mono_connector_payone_bundle_webhook:
  path: /mono-connector-payone/webhook/{contract}
  methods: ['POST']
  defaults:
    _controller: Dbp\Relay\MonoConnectorPayoneBundle\Webhook\Webhook::index
