services:
  Dbp\Relay\MonoConnectorPayunityBundle\Service\PaymentDataService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayunityBundle\Service\PayunityFlexService:
    autowire: true
    autoconfigure: true
    public: true
