services:
  Dbp\Relay\MonoConnectorPayoneBundle\Webhook\Webhook:
    autowire: true
    autoconfigure: true
    calls:
      - setAuditLogger: ['@monolog.logger.dbp_relay_mono_audit']

  Dbp\Relay\MonoConnectorPayoneBundle\Config\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayoneBundle\Persistence\PaymentDataService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_mono_connector_payone_bundle_entity_manager'

  Dbp\Relay\MonoConnectorPayoneBundle\Service\PayoneHostedCheckoutPageService:
    autowire: true
    autoconfigure: true
    public: true

  Dbp\Relay\MonoConnectorPayoneBundle\Webhook\PayoneWebhookService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayoneBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayoneBundle\Webhook\WebhookInfoCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayoneBundle\Webhook\WebhookTestCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayoneBundle\Service\PayoneService:
    autowire: true
    autoconfigure: true
    calls:
      - setAuditLogger: ['@monolog.logger.dbp_relay_mono_audit']
