services:
  Dbp\Relay\MonoConnectorPayunityBundle\Webhook\Webhook:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayunityBundle\Controller\Widget:
    autowire: true
    autoconfigure: true
    calls:
      - setAuditLogger: [ '@monolog.logger.dbp_relay_mono_audit' ]

  Dbp\Relay\MonoConnectorPayunityBundle\Config\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayunityBundle\Persistence\PaymentDataService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_mono_connector_payunity_bundle_entity_manager'

  Dbp\Relay\MonoConnectorPayunityBundle\Service\PayunityFlexService:
    autowire: true
    autoconfigure: true
    public: true

  Dbp\Relay\MonoConnectorPayunityBundle\Webhook\PayunityWebhookService:
    autowire: true
    autoconfigure: true
    calls:
      - setAuditLogger: [ '@monolog.logger.dbp_relay_mono_audit' ]

  Dbp\Relay\MonoConnectorPayunityBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayunityBundle\Webhook\WebhookCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayunityBundle\Service\PayunityService:
    autowire: true
    autoconfigure: true
    calls:
      - setAuditLogger: ['@monolog.logger.dbp_relay_mono_audit']
