services:
  Dbp\Relay\MonoConnectorPayunityBundle\Controller\Widget:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayunityBundle\Service\PaymentDataService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_mono_connector_payunity_bundle_entity_manager'

  Dbp\Relay\MonoConnectorPayunityBundle\Service\PayunityFlexService:
    autowire: true
    autoconfigure: true
    public: true
    calls:
      - setAuditLogger: ['@monolog.logger.dbp_relay_mono_audit']

  Dbp\Relay\MonoConnectorPayunityBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true
