services:
  Dbp\Relay\MonoConnectorPayoneBundle\Webhook\Webhook:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayoneBundle\Controller\Widget:
    autowire: true
    autoconfigure: true
    calls:
      - setAuditLogger: [ '@monolog.logger.dbp_relay_mono_audit' ]

  Dbp\Relay\MonoConnectorPayoneBundle\Config\ConfigurationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayoneBundle\Persistence\PaymentDataService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_mono_connector_payone_bundle_entity_manager'

  Dbp\Relay\MonoConnectorPayoneBundle\Service\PayunityFlexService:
    autowire: true
    autoconfigure: true
    public: true

  Dbp\Relay\MonoConnectorPayoneBundle\Webhook\PayunityWebhookService:
    autowire: true
    autoconfigure: true
    calls:
      - setAuditLogger: [ '@monolog.logger.dbp_relay_mono_audit' ]

  Dbp\Relay\MonoConnectorPayoneBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayoneBundle\Webhook\WebhookCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\MonoConnectorPayoneBundle\Service\PayunityService:
    autowire: true
    autoconfigure: true
    calls:
      - setAuditLogger: ['@monolog.logger.dbp_relay_mono_audit']
